import Vue from 'vue'
// 自动按需引入vant组件
import { Tab, Tabs, Checkbox, Dialog, ActionSheet, Rate, Search, Swipe, SwipeItem, Grid, GridItem, Toast, Button, Switch, Tabbar, TabbarItem, NavBar, Icon } from 'vant'
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(Icon)
Vue.use(ActionSheet)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Rate)
